### ISSUE TITLE
Condition number of a Problem

### ISSUE THREAD

**Issue by aescande** [qpsolvers/qpsolvers#220]
For now, the `cond` method of `Problem` assembles the full KKT matrix of the problem and return its condition number.

I am not sure this is fully meaningful in the presence of inequality constraints: you could have linearly dependent inequality constraints well away from the solver's iterates that would yield a bad condition number without actually disturbing the resolution.

To me, it feels like conditionning should be tied to a set of active constraints, but I don't know what are the best practices/consensus in the litterature.

**Comment by stephane-caron** [comment]
Thanks for raising this issue. I didn't give it more thought but this point is consistent with Section 4 of the OSQP paper and Equation (22) of the ProxQP paper.

Having an active set implies that ``cond`` should be a function of ``Solution`` rather than ``Problem``. But currently _qpsolvers_ does not retrieve the active set in a unified way across solver interfaces (I believe some solvers don't return it).

I suggest the following course of action:

- Deprecate ``Problem.cond`` in v3 for removal in v4.
- Open a separate feature request for handling active sets across all interfaces

**Comment by stephane-caron** [comment]
Nice :smiley: This seems even clearer to me. Feel free to open a PR for it.

**Comment by stephane-caron** [comment]
I've snapped together a quick PR for it: https://github.com/qpsolvers/qpsolvers/pull/232. Let me know if it checks for you.
